using System;

namespace LISTING_2_24_Bad_dynamic_code
{
    class MessageDisplay
    {
        public void DisplayMessage(string message)
        {
            Console.WriteLine(message);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            
            MessageDisplay m = new MessageDisplay();
            m.DisplayMessage("Hello world");

            //CTO: The keyword dynamic is used to identify items for which the C# compiler should suspend static type
            //checking.
            /*
             Such situations arise when
             using Common Object Model (COM) interop, the Document Object Model (DOM), working
             with objects generated by C# reflection, or when interworking with dynamic languages such as
             JavaScript. 
             */

            //CTO: por ser dynamic ou seja transforma o objeto em algo não tipado, o mesmo deixa compilar com chamadas de metodos desse objeto que nem existem, so dará erro de execução nesse caso
            //ou seja é como se eu declarasse um objeto PHP
            dynamic d = new MessageDisplay();
            d.Banana("hello world");
        }
    }
}
